#!/bin/bash
tasks=(
  "SaaS: Implement real JWT authentication backend"
  "SaaS: Add user registration and email verification"
  "SaaS: Implement password reset flow"
  "SaaS: Add Google/GitHub OAuth login"
  "SaaS: Create subscription tiers (Free vs Premium)"
  "SaaS: Integrate Stripe for billing"
  "SaaS: Add user profile settings page"
  "SaaS: Cloud sync of podcast subscriptions across devices"
  "SaaS: Cloud sync of listening history/play states"
  "SaaS: Add analytics dashboard for user listening habits"
  "SaaS: Implement rate limiting for API requests"
  "SaaS: Add a 'Contact Support' form"
  "SaaS: Create an admin dashboard for user management"
  "SaaS: Support multiple user profiles under one account"
  "SaaS: Implement a referral/affiliate program"
  "SaaS: Add a public 'User Profile' to share favorite podcasts"
  "SaaS: Implement push notifications for new episodes"
  "SaaS: Add Two-Factor Authentication (2FA)"
  "SaaS: Create a privacy policy and terms of service page"
  "SaaS: Add GDPR/CCPA data export and deletion tools"
  "UI/UX: Add a 'Dark Mode' and 'Light Mode' toggle"
  "UI/UX: Implement 5 new retro color themes (e.g., CRT Green, Cyberpunk Pink)"
  "UI/UX: Add drag-and-drop reordering for subscriptions"
  "UI/UX: Add a grid view vs list view toggle for podcasts"
  "UI/UX: Implement skeleton loading screens"
  "UI/UX: Add a custom retro-styled scrollbar"
  "UI/UX: Improve mobile responsiveness and touch targets"
  "UI/UX: Add swipe gestures for mobile (swipe to omit/download)"
  "UI/UX: Implement keyboard shortcuts for navigation"
  "UI/UX: Add tooltips explaining what 'Omit' and 'Sync' do"
  "UI/UX: Create an onboarding tutorial overlay for new users"
  "UI/UX: Add sound effects for UI interactions (clicks, sync complete)"
  "UI/UX: Make the 'Cassette Spin' animation react to actual transfer speed"
  "UI/UX: Show a visual storage capacity bar for the connected USB drive"
  "UI/UX: Add a 'Clear Cache' button in the settings"
  "UI/UX: Implement infinite scrolling for long episode lists"
  "UI/UX: Add a 'Back to Top' button"
  "UI/UX: Create custom error pages (404, 500) with retro art"
  "UI/UX: Add a 'What's New' modal for app updates"
  "UI/UX: Implement internationalization (i18n) for multiple languages"
  "Podcasts: Add OPML file import for migrating from other apps"
  "Podcasts: Add OPML file export"
  "Podcasts: Implement podcast search via iTunes/Apple Podcasts API"
  "Podcasts: Add custom categories/folders for subscriptions"
  "Podcasts: Add tag support for episodes"
  "Podcasts: Implement a 'Favorites' or 'Starred' list"
  "Podcasts: Add a 'Listen Later' queue"
  "Podcasts: Support private/premium RSS feeds (HTTP Auth)"
  "Podcasts: Parse and display episode show notes (HTML to Text)"
  "Podcasts: Support chapter markers within episodes"
  "Podcasts: Automatically fetch high-res podcast cover art"
  "Podcasts: Allow manual override of podcast titles"
  "Podcasts: Allow manual override of episode titles"
  "Podcasts: Implement a 'Mark all as played/omitted' button"
  "Podcasts: Add a filter for 'Downloaded', 'Unplayed', 'Omitted'"
  "Podcasts: Support sorting episodes by Date, Title, or Duration"
  "Podcasts: Add a 'Trending/Discover' page for new podcasts"
  "Podcasts: Implement a recommendation engine based on subscriptions"
  "Podcasts: Support fetching feeds via WebSockets for real-time updates"
  "Podcasts: Detect and handle dead/broken RSS feeds gracefully"
  "Audio: Build an in-app audio player for previewing episodes"
  "Audio: Implement play/pause, seek, and volume controls in the player"
  "Audio: Add playback speed controls (1.5x, 2x)"
  "Audio: Add a 'Skip Silence' feature using Web Audio API"
  "Audio: Save and resume playback position in the app"
  "Audio: Add a global mini-player locked to the bottom of the screen"
  "Audio: Implement a visual waveform display for playing audio"
  "Audio: Add an sleep timer for the in-app player"
  "Audio: Support background audio playback in the browser"
  "Audio: Implement Media Session API for OS-level media controls"
  "Audio: Add a 'Boost Vocals' EQ preset using Web Audio API"
  "Audio: Show remaining time for current episode in the tab title"
  "Audio: Allow user to clip/trim an episode before syncing"
  "Audio: Support playing local cached files without internet"
  "Audio: Add a 'continuous play' mode to auto-start next episode"
  "Audio: Implement a 'Karaoke' mode if transcripts are available in RSS"
  "Audio: Add a volume normalization (compression) filter"
  "Audio: Provide an audio quality toggle for streaming"
  "Audio: Add picture-in-picture mode for video podcasts (if supported later)"
  "Audio: Cast/AirPlay support from the web player"
  "Hardware/Sync: Add setting to auto-eject USB drive after sync completes"
  "Hardware/Sync: Warn user if USB drive doesn't have enough free space"
  "Hardware/Sync: Add setting to delete files from USB after 30 days"
  "Hardware/Sync: Implement bi-directional sync (read play state from USB if supported)"
  "Hardware/Sync: Transcode non-MP3 files to MP3 on the fly via WebAssembly (FFmpeg)"
  "Hardware/Sync: Downsample MP3 bitrates on the fly to save space"
  "Hardware/Sync: Rewrite ID3 tags on downloaded MP3s to ensure phone compatibility"
  "Hardware/Sync: Inject cover art into the MP3 ID3 tags"
  "Hardware/Sync: Create m3u playlist files on the USB drive automatically"
  "Hardware/Sync: Support chunked file transfers for very large episodes"
  "Hardware/Sync: Add a 'Sync History' log to see what was copied when"
  "Hardware/Sync: Add retry logic for failed file writes"
  "Hardware/Sync: Allow user to specify custom folder structure on USB (e.g., /Podcasts/PodcastName/)"
  "Hardware/Sync: Add setting to prepend date to filename (e.g., 2026-03-02_Episode.mp3)"
  "Hardware/Sync: Check file hashes (MD5) to avoid re-syncing existing files"
  "Hardware/Sync: Support syncing to multiple USB drives simultaneously"
  "Hardware/Sync: Implement background sync using Background Sync API (if feasible)"
  "Hardware/Sync: Allow user to cap the maximum folder size on the USB drive"
  "Hardware/Sync: Automatically clean up orphaned files in the /Podcasts folder"
  "Hardware/Sync: Generate a summary text file on the USB with episode descriptions"
)

for task in "${tasks[@]}"; do
  gh project item-create 1 --owner mbryantuk --title "$task" > /dev/null
done
